# I. NumPy.

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy.**

**Рішення з циклами будуть оцінені в 0 балів.**

1. (2б) Імпортувати numpy загальноприйнятим способом.

In [1]:
import numpy as np

2. (3б) Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [2]:
grades = [85, 90, 78, 92, 88]
grades_array = np.array(grades)

grades_array

array([85, 90, 78, 92, 88])

3. (4б) Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [3]:
price_list = [
    [2.5, 3.0, 1.8, 5.5],
    [2.0, 2.5, 1.5, 4.5],
    [2.2, 2.8, 1.6, 5.0]
]

price_matrix = np.array(price_list)
price_matrix

array([[2.5, 3. , 1.8, 5.5],
       [2. , 2.5, 1.5, 4.5],
       [2.2, 2.8, 1.6, 5. ]])

4. (3б) Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [4]:
print(grades_array.dtype)
print(price_matrix.dtype)

int32
float64


5. (3б) Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [6]:
print("Shape of grades_array:", grades_array.shape)
print("Shape of price_matrix:", price_matrix.shape)


Shape of grades_array: (5,)
Shape of price_matrix: (3, 4)


6. (5б) Поясніть, чому для масиву із завдання 2 ми отримали саме такий результат. На основі того ж самого масиву з цілими числами-оцінками створіть вектор-стовбець (не вектор-рядок!).

Властивість shape завжди повертає кортеж, у випадку одновимірного масиву це кортеж з одним елементом - розміром цього масиву.

In [9]:
column_vector = grades_array.reshape(-1, 1)
column_vector

array([[85],
       [90],
       [78],
       [92],
       [88]])

7. (6б) Тезисно поясніть різницю між Python списком та NumPy масивом.

Numpy - це статичний масив, python список - динамічний.
Масив numpy підтримує індексування елементів, як і списки, але існують векторизовані функції (швидший аналог map для списків).
Також у масивах numpy зберігається лише один тип даних, у списках можуть бути об'єкти різних типів.

8. (7б) Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [10]:
import numpy as np

revenue = np.linspace(0, 1000.50, num=7)
revenue


array([   0.  ,  166.75,  333.5 ,  500.25,  667.  ,  833.75, 1000.5 ])

9. (8б) Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [20]:
import numpy as np

# Create two arrays
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4, 5, 6]])

vertical_concatenation = np.concatenate((array1, array2), axis=0)
print("Vertical concatenation:")
print(vertical_concatenation)

horizontal_concatenation = np.concatenate((array1, array2), axis=1)
print("Horizontal concatenation:")
print(horizontal_concatenation)

Vertical concatenation:
[[1 2 3]
 [4 5 6]]
Horizontal concatenation:
[[1 2 3 4 5 6]]


10. (12б) Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [31]:
def transpose_array(arr):
    """
    Transposes the input array using the reshape method.

    Parameters:
    arr (numpy.ndarray): The input array.

    Returns:
    numpy.ndarray: The transposed array.
    """
    return np.reshape(arr, (arr.shape[1], arr.shape[0]))

transpose_array(np.array([[1, 2, 3], [4, 5, 6]]))

array([[1, 2],
       [3, 4],
       [5, 6]])

11. (7б) Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [34]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

addition_result = array1 + array2
print("Element-wise addition:")
print(addition_result)

subtraction_result = array1 - array2
print("Element-wise subtraction:")
print(subtraction_result)

number = 2
multiplication_result = array1 * number
print("Multiplication of array by a number:")
print(multiplication_result)

elementwise_multiplication_result = array1 * array2
print("Element-wise multiplication:")
print(elementwise_multiplication_result)

matrix_multiplication_result = np.dot(array1, array2)
print("Matrix multiplication:")
print(matrix_multiplication_result)


Element-wise addition:
[5 7 9]
Element-wise subtraction:
[-3 -3 -3]
Multiplication of array by a number:
[2 4 6]
Element-wise multiplication:
[ 4 10 18]
Matrix multiplication:
32


12. (7б) Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [38]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10,11,12]])

minimum = np.min(matrix)

maximum = np.max(matrix)

sum_of_numbers = np.sum(matrix)

minimum_per_row = np.min(matrix, axis=1)

maximum_per_column = np.max(matrix, axis=0)

minimum, maximum, sum_of_numbers, minimum_per_row, maximum_per_column


(1, 12, 78, array([ 1,  4,  7, 10]), array([10, 11, 12]))

13. (6б) Використовуючи двовимірний масив з попереднього завдання, отримайте значення першого та другого стовпчика всіх рядків, окрім першого та останнього.

In [39]:
selected_columns = matrix[1:-1, :2]
selected_columns


array([[4, 5],
       [7, 8]])

14. (7б) Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [40]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]])


unique_values, frequencies = np.unique(matrix, return_counts=True)

for value, frequency in zip(unique_values, frequencies):
    print(f"Value: {value}, Frequency: {frequency}")


Value: 1, Frequency: 2
Value: 2, Frequency: 2
Value: 3, Frequency: 2
Value: 4, Frequency: 2
Value: 5, Frequency: 2
Value: 6, Frequency: 2


15. (20б) Тривимірні масиви (тензори) дуже широко використовуються для вирішення задач компʼютерного зору, де один вимір відповідає за висоту зображення у пікселях, другий - за ширину зображення у пікселях, а третій - RGB шар. Значення такого масиву зазвичай знаходяться у проміжку від 0 до 255, що є позначенням для інтенсивності того чи іншого кольору (див. зображення нижче). Пропоную вам, маючи знання з numpy, торкнутись до світу роботи з особливим типом даних - зображеннями. Сподіваюсь, когось з вас це зацікавить.

Завдання:
1. Визначити змінні для висоти та ширини майбутнього зображення. Присвоїти їм значення 480 та 720 відповідно.
2. Визначте змінну для зображення, яка прийматиме тривимірний масив відповідного розміру з пустими значеннями, які ми заповнимо пізніше. Тип даних масиву вкажіть np.uint8 (це спеціальний тип даних для шкали пікселів зображень).
3. Розділимо зображення навпіл по висоті. Для цього обчисліть серединний піксель та збережіть його у змінну. Будьте уважні, це число буде використовуватися для слайсингу, де крайні значення не включаються у діапазон.
4. Розфарбуємо верхню частину зображення. За допомогою слайсингу на змінній з зображенням, виділіть першу половину пікселів по висоті, залишаючи всі пікселі в рядках по ширині та глибині (всі 3 RGB шари). Та призначте їй кортеж (0, 87, 184), що позначає колір у трьох RGB шарах відповідно.
5. Тепер розфарбуємо нижню частину зображення. За допомогою слайсингу на змінній з зображенням, виділіть другу половину пікселів по висоті, залишаючи всі пікселі в рядках по ширині та глибині (всі 3 RGB шари). Та призначте їй кортеж (255, 215, 0), що позначає колір у трьох RGB шарах відповідно. Вже здогадуєтесь, що за зображення ви створюєте?)
6. На останньому рядку комірки просто введіть назву змінної з зображенням.


![текст посилання](https://drive.google.com/uc?id=15vio4RLXdoRDKvulHvpk7u9RQxbe_qXL)

![текст посилання](https://drive.google.com/uc?id=1c7Z9yxNgFoMYFXUmmzNEd9cJDZE2TWov)

![текст посилання](https://drive.google.com/uc?id=1d9bT_fqbxCV7_b8c8Cbx2KEGVJUKenqh)

![текст посилання](https://drive.google.com/uc?id=16r2XB6MO-E9dltIqsbumtoIQhkRfsbZ_)


In [42]:
height = 480
width = 720

image = np.empty((height, width, 3), dtype=np.uint8)

middle_pixel = height // 2

image[:middle_pixel, :, :] = (0, 87, 184)

image[middle_pixel:, :, :] = (255, 215, 0)

image

array([[[  0,  87, 184],
        [  0,  87, 184],
        [  0,  87, 184],
        ...,
        [  0,  87, 184],
        [  0,  87, 184],
        [  0,  87, 184]],

       [[  0,  87, 184],
        [  0,  87, 184],
        [  0,  87, 184],
        ...,
        [  0,  87, 184],
        [  0,  87, 184],
        [  0,  87, 184]],

       [[  0,  87, 184],
        [  0,  87, 184],
        [  0,  87, 184],
        ...,
        [  0,  87, 184],
        [  0,  87, 184],
        [  0,  87, 184]],

       ...,

       [[255, 215,   0],
        [255, 215,   0],
        [255, 215,   0],
        ...,
        [255, 215,   0],
        [255, 215,   0],
        [255, 215,   0]],

       [[255, 215,   0],
        [255, 215,   0],
        [255, 215,   0],
        ...,
        [255, 215,   0],
        [255, 215,   0],
        [255, 215,   0]],

       [[255, 215,   0],
        [255, 215,   0],
        [255, 215,   0],
        ...,
        [255, 215,   0],
        [255, 215,   0],
        [255, 215,   0]]

# Бонус для тих, хто виконав останнє завдання.

Слава Україні! 🇺🇦